### ISSUE TITLE
Noclip with V key is not working 

### ISSUE THREAD

**Issue by sousou63** [sousou63/DarkRP-old#96]
If you have the right permission, no clip is only working with /noclip, the V key return an exception

**Comment by sousou63** [comment]
I've pushed a commit with a potential fix but need actual test in-game and not in-editor

**Comment by QueenPM** [comment]
Potentially fixed this bug.

It seems to have been caused by `PlayerConnObject` not getting properly referenced in `MovementController.cs`. So added a function to check for it before attempting to noclip.

Also added `try...catch` inside of the function and log us a warning. That way we'll be able to tell if its fixed or not.

**Comment by dancore-san** [comment]
Seems fixed to me

**Comment by EuroBlue** [comment]
![image](https://github.com/user-attachments/assets/e6b41da4-4bd4-4e49-b54b-35fd61cfc16f)
Doesn't work and when one player tries to use it makes it for everyone

**Comment by QueenPM** [comment]
I've got a potential fix for it.

**Comment by dancore-san** [comment]
I'm pretty sure thats a chat command issue

**Comment by sousou63** [comment]
seems fixed now
